### ISSUE TITLE
Issueベースの開発 レビュー依頼

### ISSUE THREAD

**Issue by jarriemorrow** [jarriemorrow/saizeriya#14]
### 実装予定の機能

- [ ] ユーザー登録（ログイン機能）
- [ ] マイリスト
- [ ] コースメニュー、アレンジ・ペアリングメニューの登録
- [ ] 各メニューのお気に入り登録
- [ ] 各メニュー検索機能
- [ ] Xへの投稿機能

### 必要なページ
【未ログイン利用可】
- [ ] トップページ
- [ ] ユーザー新規登録ページ
- [ ] ログインページ
- [ ] パスワード忘れページ
- [ ] 投稿一覧ページ
- [ ] 投稿メニュー詳細ページ

【ログイン後利用可能】
- [ ] メニュー登録ページ
- [ ] マイページ
- [ ] プロフィール変更ページ
- [ ] お気に入り一覧

**Comment by ky0613** [comment]
以下のようにprojectsが表示されないので紐付けをお願いします。
[![Image from Gyazo](https://i.gyazo.com/dfbc0ed54f14ea3be7cc44c9cd7fd7db.png)](https://gyazo.com/dfbc0ed54f14ea3be7cc44c9cd7fd7db)

**Comment by jarriemorrow** [comment]
失礼しました。公開範囲をpublicに変更いたしました。

**Comment by ky0613** [comment]
対応ありがとうございます。
以下のようにissueが一つしかないようなので、全てのissueが実装順に並ぶように対応お願いします。
[![Image from Gyazo](https://i.gyazo.com/37cce833294e97b3a41d225489e22ca1.png)](https://gyazo.com/37cce833294e97b3a41d225489e22ca1)

**Comment by tarakish** [comment]
コメントが無いようなのでご確認をお願いします。
なにか対応を行った場合はどういうことを行ったか、レビュアーに求めるアクションなどを記載するようにしましょう！

**Comment by jarriemorrow** [comment]
承知しました。　

Issueを追加し、並び替えを行いました。
レビューよろしくお願いいたします。

**Comment by tarakish** [comment]
修正確認しました👍
ストーリーポイントがつけられていないようなので、プロジェクトマネジメントのカリキュラムを確認し、ストーリーポイントを付与するようにしてください。

**Comment by jarriemorrow** [comment]
ストーリーポイントを反映させました。

**Comment by tarakish** [comment]
各Issueのストーリーポイントが確認できなかったので再度ご確認をお願いします。
![スクリーンショット 2024-06-15 17 39 11](https://github.com/jarriemorrow/saizeriya/assets/71510236/d2783b15-8c67-4a9d-b4e5-59bfba838194)
![スクリーンショット 2024-06-15 17 53 03](https://github.com/jarriemorrow/saizeriya/assets/71510236/c6cd4d9e-986e-4c56-a57d-47f2cc334553)

**Comment by jarriemorrow** [comment]
何度もすみません。

ストーリーポイントを設定しました。

**Comment by kashiwagi-rena** [comment]
お疲れ様です。
ストリートポイント確認が取れました。

READMEの方にAWS S3の使用を記載しておられますが、画像保存はご検討しておいでですか？
もし、画像保存される場合は、画像に関してのissueの追記をお願いいたします。

ユーザー登録機能で使用するgemを現段階で決定しておくと次が立てやすいため、そちらの検討も行なってみてください。

**Comment by jarriemorrow** [comment]
ありがとうございます。

S3の件、失念しておりました。こちらはissueに追記いたしました。
また使用gemは、ユーザー登録にSorcery、画像保存にはcarriewaveを使用する予定です。

**Comment by Tsuchiya2** [comment]
対応ありがとうございます。
私からもコメントします。

---

やや粒度が大きいためか、または見通しが難しいためか、ストーリーポイントが全体的に少し大きめに感じました。ポイント1, 2 くらいになるくらいに細かくissue化することで、不明瞭な部分、明瞭な部分が可視化されますし、進捗を感じながら開発を進めることができます。もう少しissueを細分化しましょう。

また、以下の項目はMVP後で良いかもと感じたものになります。「MVP後」の列を作って、そちらにカードを配置しておきましょう。

- テスト
- パスワードリセット

※デプロイは rails new が終わった直後に行いましょう。

**Comment by jarriemorrow** [comment]
ありがとうございます。
少し粒度を細かく設定し、細分化してみました。
レビューお願いいたします。

**Comment by shota-hope** [comment]
修正ありがとうございます、LGTMです！

(※もう少し分割できる（出来れば分割した方がよさそうな）issueは見受けられますが、
実装を進めながらissueが大きすぎるなと感じたら適宜分割をするように進めると良いと思います。)

**Comment by jarriemorrow** [comment]
> 修正ありがとうございます、LGTMです！
> 
> (※もう少し分割できる（出来れば分割した方がよさそうな）issueは見受けられますが、 実装を進めながらissueが大きすぎるなと感じたら適宜分割をするように進めると良いと思います。)

ありがとうございます。手直ししながら進めていきたいと思います。
