### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by jarriemorrow** [jarriemorrow/saizeriya#38]
## 各種情報
サービス名；未定です（本リリース時に決定します）
サービスURL： https://saizeri.fly.dev/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x]   1.ユーザー登録（ログイン機能）
- [x]   2.コースメニュー、アレンジ・ペアリングメニューの登録
- [x]   3.各メニューのお気に入り登録
- [x]  4.各メニュー検索機能
- [ ]  5.Xへの投稿機能　→　後述します

投稿ページ（new,edit)遷移後、ブラウザバックして再度投稿ページに移動し「メニューを追加」ボタンを押下すると複数個のメニューが出現するバグがあります。
こちらについてはMVP後に修正でも大丈夫との回答を富田講師よりいただいております。

## READMEレビュー時から変更した機能
Xへの投稿機能を実装予定でしたが、投稿後新規ユーザーがサービス利用に繋がるか疑問だったため一旦取りやめました。
投稿時の画像登録機能は本リリース時にページのデザインと合わせて調整する必要があると考えたため、MVP後に変更しました。
※このサービスは主にスマートフォンでの利用を考えているため、投稿画面のデザインと共に画像の表示機能のデザインを考えたいためです。

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/48c483109b011eb173ad3193f8db51f5.png)](https://gyazo.com/48c483109b011eb173ad3193f8db51f5)

[![Image from Gyazo](https://i.gyazo.com/4699137ef15f53d15e78f8167b52e920.png)](https://gyazo.com/4699137ef15f53d15e78f8167b52e920)

[![Image from Gyazo](https://i.gyazo.com/0afbd6679ef829dc4817d3a35d5f874c.png)](https://gyazo.com/0afbd6679ef829dc4817d3a35d5f874c)

[![Image from Gyazo](https://i.gyazo.com/bd886fbd6affff201da651d5640814cc.png)](https://gyazo.com/bd886fbd6affff201da651d5640814cc)

[![Image from Gyazo](https://i.gyazo.com/a80268a8f070a2d8e139134ef1576e9b.png)](https://gyazo.com/a80268a8f070a2d8e139134ef1576e9b)

[![Image from Gyazo](https://i.gyazo.com/d1d292352652b6932f78ed8f653cf25a.png)](https://gyazo.com/d1d292352652b6932f78ed8f653cf25a)

[![Image from Gyazo](https://i.gyazo.com/b73194046853355a961b197c0dffa591.png)](https://gyazo.com/b73194046853355a961b197c0dffa591)

**Comment by tmtkzk0823** [comment]
ご提出ありがとうございます。
MVP機能を満たしているとおもいます。
LGTMです！

**Comment by jarriemorrow** [comment]
> ご提出ありがとうございます。 MVP機能を満たしているとおもいます。 LGTMです！

ありがとうございます！！引き続き本リリースに向けてがんばります！
